### ISSUE TITLE
Move to pypdf

### ISSUE THREAD

**Issue by MartinThoma** [py-pdf/pypdf#1488]
For first-time users, it's confusing that there is pyPdf, PyPDF2, PyPDF3, and PyPDF4. Also non-frequent users get confused about the capitalization of PyPDF2. On StackOverflow, people regularly ask questions about `pypdf` which are actually about `PyPDF2`.

Hence we should move "back" to `pypdf` (all lowercase, no dashes/underscores).

## Transition

I will make one last release (+ potentially bugfix-releases) for PyPDF2. That will then be identical (except for the package name) to the same version of pypdf.

So `PyPDF2==3.0.0` would be almost equal to `pypdf==4.0.0`, so that people just need re-name the package they import from `PyPDF2` to `pypdf` + change the package they install.

## TODO
- [x] Rename GitHub repository from `PyPDF2` to `pypdf`
- [x] Rename Package inside this repo `pypdf`
- [ ] Try to get the pypdf github organization: https://github.com/orgs/community/discussions/41360 - might be impossible, though https://github.com/orgs/community/discussions/23468

**Comment by MartinThoma** [comment]
There is a conda forge package for PyPDF2: https://anaconda.org/conda-forge/pypdf2

We should make one for pypdf as well

**Comment by MasterOdin** [comment]
Looking at the PyPDF2 pypa page, it doesn't look like the notice at the top of the README about moving to pypdf got published there. May be worth making a 3.0.1 release with that info, and also perhaps a deprecation notice in the `__init__.py` itself for those that just blindly install the dependency without going to pypa?

**Comment by MartinThoma** [comment]
@MasterOdin Good point! Like that: https://github.com/py-pdf/pypdf/pull/1517 ?

**Comment by huonw** [comment]
I noticed that there's some inconsistent doc links that may relate to this switch: 

- the README (etc.) links to https://pypdf.readthedocs.io/en/stable/
- Github's sidebar links to https://pypdf2.readthedocs.io/en/latest/ (note: extra 2)
  ![image](https://user-images.githubusercontent.com/1203825/210669119-e626c1c1-58a3-4a21-932c-25779bb1b56e.png)

**Comment by MartinThoma** [comment]
Fixed! Thank you @huonw

**Comment by epicfaace** [comment]
> * Try to get the pypdf github organization: https://github.com/orgs/community/discussions/41360 - might be impossible, though https://github.com/orgs/community/discussions/23468

Hey @MartinThoma -- did you try contacting github support? They should be pretty responsive on this I believe!

**Comment by MartinThoma** [comment]
I've contacted them, but they said there is nothing they can do
